apiVersion: batch/v1
kind: CronJob
metadata:
  name: visits-cron
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: curl
              image: curlimages/curl
              args: ["-sS", "http://go-k8s-lab/visits"]