apiVersion: batch/v1
kind: Job
metadata:
  name: visits-job
spec:
  completions: 3
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: curl
          image: curlimages/curl
          args: ["-sS", "http://go-k8s-lab/visits"]